[package]
name = "zero2prod"
version = "0.1.0"
edition = "2018"

[lib]
path = "src/lib.rs"
name = "zero2prod"

[dependencies]
actix-web = "4.0.0-beta.8"

[dev-dependencies]
actix-rt = "2"
reqwest = "0.11"
tokio = "1"
